FROM node:24-slim

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./ 

RUN npm ci

COPY --chown=node:node . . 

RUN npx prisma generate

EXPOSE 3000

USER node

CMD ["npm", "run", "dev"]